// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// Host url for UltraDNS rest api.
func GetHosturl(ctx *pulumi.Context) string {
	return config.Get(ctx, "ultradns:hosturl")
}

// Password for UltraDNS rest api.
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "ultradns:password")
}

// User name for UltraDNS rest api.
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "ultradns:username")
}
