# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

hosturl: Optional[str]
"""
Host url for UltraDNS rest api.
"""

password: Optional[str]
"""
Password for UltraDNS rest api.
"""

username: Optional[str]
"""
User name for UltraDNS rest api.
"""

