# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .record import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import mark-bixler_ultradns.config as __config
    config = __config
else:
    config = _utilities.lazy_import('mark-bixler_ultradns.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "ultradns",
  "mod": "index/record",
  "fqn": "mark-bixler_ultradns",
  "classes": {
   "ultradns:index/record:Record": "Record"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "ultradns",
  "token": "pulumi:providers:ultradns",
  "fqn": "mark-bixler_ultradns",
  "class": "Provider"
 }
]
"""
)
