// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this data source to get detailed information of Directional (DIR) pool records.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ultradns from "@pulumi/ultradns";
 *
 * const dirpool = pulumi.output(ultradns.getDirPool({
 *     ownerName: "www",
 *     recordType: "A",
 *     zoneName: "example.com.",
 * }));
 * ```
 */
export function getDirPool(args: GetDirPoolArgs, opts?: pulumi.InvokeOptions): Promise<GetDirPoolResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("ultradns:index/getDirPool:getDirPool", {
        "ownerName": args.ownerName,
        "recordType": args.recordType,
        "zoneName": args.zoneName,
    }, opts);
}

/**
 * A collection of arguments for invoking getDirPool.
 */
export interface GetDirPoolArgs {
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    ownerName: string;
    /**
     * (String) Must be formatted as a well-known resource record type (A), or the corresponding number for the type (1).<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     */
    recordType: string;
    /**
     * (String) Name of the zone.
     */
    zoneName: string;
}

/**
 * A collection of values returned by getDirPool.
 */
export interface GetDirPoolResult {
    /**
     * (Computed) (String) When there is a conflict between a matching GeoIP group and a matching SourceIP group, this will determine which should take precedence. This only applies to a mixed pool (contains both GeoIP and SourceIP data).
     */
    readonly conflictResolve: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * (Computed) (Boolean) Whether to ignore the EDNSO (which is an extended label type allowing for greater DNS messaging size) Client Subnet data when available in the DNS request.</br>
     * `false`= EDNSO data will be used for IP directional routing.</br>
     * `true` = EDNSO data will not be used and IP directional routing decisions will always use the IP address of the recursive server.
     */
    readonly ignoreEcs: boolean;
    /**
     * (Computed) (Block Set, Max: 1) Nested block describing certain geographical territories and IP addresses that will not get a response if they try to access the directional pool. The structure of this block is described below.
     */
    readonly noResponses: outputs.GetDirPoolNoResponse[];
    readonly ownerName: string;
    /**
     * (Computed) (String) Allows for an additional description of the Directional (DIR) pool.
     */
    readonly poolDescription: string;
    /**
     * (Computed) (Block Set, Min: 1) List of nested blocks describing the pool records. The structure of this block is described below.
     */
    readonly rdataInfos: outputs.GetDirPoolRdataInfo[];
    readonly recordType: string;
    /**
     * (Computed) (Integer) The time to live (in seconds) for the corresponding record in rdata. Must be a value between 0 and 2147483647, inclusive.
     */
    readonly ttl: number;
    readonly zoneName: string;
}

export function getDirPoolOutput(args: GetDirPoolOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDirPoolResult> {
    return pulumi.output(args).apply(a => getDirPool(a, opts))
}

/**
 * A collection of arguments for invoking getDirPool.
 */
export interface GetDirPoolOutputArgs {
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    ownerName: pulumi.Input<string>;
    /**
     * (String) Must be formatted as a well-known resource record type (A), or the corresponding number for the type (1).<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     */
    recordType: pulumi.Input<string>;
    /**
     * (String) Name of the zone.
     */
    zoneName: pulumi.Input<string>;
}
