// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use this data source to get detailed information of standard DNS records.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ultradns from "@pulumi/ultradns";
 *
 * const record = pulumi.output(ultradns.getRecord({
 *     ownerName: "www",
 *     recordType: "A",
 *     zoneName: "example.com.",
 * }));
 * ```
 */
export function getRecord(args: GetRecordArgs, opts?: pulumi.InvokeOptions): Promise<GetRecordResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("ultradns:index/getRecord:getRecord", {
        "ownerName": args.ownerName,
        "recordType": args.recordType,
        "zoneName": args.zoneName,
    }, opts);
}

/**
 * A collection of arguments for invoking getRecord.
 */
export interface GetRecordArgs {
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    ownerName: string;
    /**
     * (String) Must be formatted as the well-known resource record type (A, AAAA, TXT, etc.) or the corresponding number for the type, between 1 and 65535.<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     * `NS (2)`
     * `CNAME (5)`
     * `PTR (12)`
     * `MX (15)`
     * `TXT (16)`
     * `AAAA (28)`
     * `SRV (33)`
     * `SSHFP (44)`
     * `APEXALIAS (65282)`
     */
    recordType: string;
    /**
     * (String) Name of the zone.
     */
    zoneName: string;
}

/**
 * A collection of values returned by getRecord.
 */
export interface GetRecordResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ownerName: string;
    /**
     * (Computed) (String List) The data for the record displayed as the BIND presentation format for the specified RRTYPE.<br/>
     * Example : For a SRV record, the format of data is ["priority weight port target"] (["2 2 523 example.com."]).
     */
    readonly recordDatas: string[];
    readonly recordType: string;
    /**
     * (Computed) (Integer) The time to live (in seconds) for the record. Must be a value between 0 and 2147483647, inclusive.
     */
    readonly ttl: number;
    readonly zoneName: string;
}

export function getRecordOutput(args: GetRecordOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetRecordResult> {
    return pulumi.output(args).apply(a => getRecord(a, opts))
}

/**
 * A collection of arguments for invoking getRecord.
 */
export interface GetRecordOutputArgs {
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    ownerName: pulumi.Input<string>;
    /**
     * (String) Must be formatted as the well-known resource record type (A, AAAA, TXT, etc.) or the corresponding number for the type, between 1 and 65535.<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     * `NS (2)`
     * `CNAME (5)`
     * `PTR (12)`
     * `MX (15)`
     * `TXT (16)`
     * `AAAA (28)`
     * `SRV (33)`
     * `SSHFP (44)`
     * `APEXALIAS (65282)`
     */
    recordType: pulumi.Input<string>;
    /**
     * (String) Name of the zone.
     */
    zoneName: pulumi.Input<string>;
}
