// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this data source to get detailed information of Simple Load Balancing (SLB) pool records.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ultradns from "@pulumi/ultradns";
 *
 * const slbpool = pulumi.output(ultradns.getSlbPool({
 *     ownerName: "www",
 *     recordType: "A",
 *     zoneName: "example.com.",
 * }));
 * ```
 */
export function getSlbPool(args: GetSlbPoolArgs, opts?: pulumi.InvokeOptions): Promise<GetSlbPoolResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("ultradns:index/getSlbPool:getSlbPool", {
        "ownerName": args.ownerName,
        "recordType": args.recordType,
        "zoneName": args.zoneName,
    }, opts);
}

/**
 * A collection of arguments for invoking getSlbPool.
 */
export interface GetSlbPoolArgs {
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    ownerName: string;
    /**
     * (String) Must be formatted as a well-known resource record type (A or AAAA), or the corresponding number for the type (1 or 28).<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     * `AAAA (28)`
     */
    recordType: string;
    /**
     * (String) Name of the zone.
     */
    zoneName: string;
}

/**
 * A collection of values returned by getSlbPool.
 */
export interface GetSlbPoolResult {
    /**
     * (Required) (Block Set) Nested block describing the information for the backup record. The structure of this block is described below.
     */
    readonly allFailRecords: outputs.GetSlbPoolAllFailRecord[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * (Computed) (Block Set) Nested block describing the information for the monitor. The structure of this block is described below.
     */
    readonly monitors: outputs.GetSlbPoolMonitor[];
    readonly ownerName: string;
    /**
     * (Computed) (String) An optional description of the Simple Load Balancing (SLB) field.
     */
    readonly poolDescription: string;
    /**
     * (Required) (Block Set, Max: 5) Nested block describing the pool records. The structure of this block is described below.
     */
    readonly rdataInfos: outputs.GetSlbPoolRdataInfo[];
    readonly recordType: string;
    /**
     * (Computed) (String) Specifies the sensitivity to the number of regions that need to fail for the backup record to be made active.
     */
    readonly regionFailureSensitivity: string;
    /**
     * (Required) (String) The method used to select which record is returned from the primary record pool. valid values are:</br>
     * `PRIORITY_HUNT` – The sequence of the records listed in the primary record pool determines the priority. The first record listed is the highest priority record. Once a record starts being served, it will always be served until the probe detects a failure on this record, or, the record is set to FORCED_INACTIVE.</br>
     * `RANDOM` – A random record is returned from the following set of primary records.</br>
     * `ROUND_ROBIN` - A record is returned in (a round robin fashion) rotation, based upon the priority of the following active set of records.
     */
    readonly responseMethod: string;
    /**
     * (Required) (String) It determines if records will be selected from the Primary Records pool , or, from the All Fail Record. Valid values are:</br>
     * `AUTO_SELECT`: Serving method switches from serving Primary Records, to All Fail Record based upon probe results, and the Forced State of the Primary Records.</br>
     * `SERVE_PRIMARY`: Only the Primary Records are served based upon the probe results and the Forced State of the Primary Records.</br>
     * `SERVE_ALL_FAIL`: Only the All Fail Record will be served, ignoring the probe results and the Forced State of the Primary Records.
     */
    readonly servingPreference: string;
    /**
     * (Computed) (String)  Current status of the serving record. Valid values are:</br>
     * `OK`- Priority record(s) are being served.</br>
     * `WARNING` – One of the priority records is not being served due to the monitor detecting a failure, but there is still a priority record to be served.</br>
     * `CRITICAL` – The backup All Fail record is being served due to the monitor detecting a failure.
     */
    readonly status: string;
    /**
     * (Computed) (Integer) The time to live (in seconds) for the record. Must be a value between 0 and 2147483647, inclusive.
     */
    readonly ttl: number;
    readonly zoneName: string;
}

export function getSlbPoolOutput(args: GetSlbPoolOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSlbPoolResult> {
    return pulumi.output(args).apply(a => getSlbPool(a, opts))
}

/**
 * A collection of arguments for invoking getSlbPool.
 */
export interface GetSlbPoolOutputArgs {
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    ownerName: pulumi.Input<string>;
    /**
     * (String) Must be formatted as a well-known resource record type (A or AAAA), or the corresponding number for the type (1 or 28).<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     * `AAAA (28)`
     */
    recordType: pulumi.Input<string>;
    /**
     * (String) Name of the zone.
     */
    zoneName: pulumi.Input<string>;
}
