// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this data source to get detailed information of Simple Monitor/Failover (SF) pool records.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ultradns from "@pulumi/ultradns";
 *
 * const sfpool = pulumi.output(ultradns.getSfPool({
 *     ownerName: "www",
 *     recordType: "A",
 *     zoneName: "example.com.",
 * }));
 * ```
 */
export function getSfPool(args: GetSfPoolArgs, opts?: pulumi.InvokeOptions): Promise<GetSfPoolResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("ultradns:index/getSfPool:getSfPool", {
        "ownerName": args.ownerName,
        "recordType": args.recordType,
        "zoneName": args.zoneName,
    }, opts);
}

/**
 * A collection of arguments for invoking getSfPool.
 */
export interface GetSfPoolArgs {
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    ownerName: string;
    /**
     * (String) Must be formatted as a well-known resource record type (A or AAAA) or the corresponding number for the type (1 or 28).<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     * `AAAA (28)`
     */
    recordType: string;
    /**
     * (String) Name of the zone.
     */
    zoneName: string;
}

/**
 * A collection of values returned by getSfPool.
 */
export interface GetSfPoolResult {
    /**
     * (Computed) (Block Set) Nested block describing the information for the backup record. The structure of this block is described below.
     */
    readonly backupRecords: outputs.GetSfPoolBackupRecord[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * (Computed) (String) An optional description of the live record.
     */
    readonly liveRecordDescription: string;
    /**
     * (Computed) (Block Set) Nested block describing the information for the monitor. The structure of this block is described below.
     */
    readonly monitors: outputs.GetSfPoolMonitor[];
    readonly ownerName: string;
    /**
     * (Computed) (String) An optional description of the Simple Failover field.
     */
    readonly poolDescription: string;
    /**
     * (Computed) (String List) The list of IPv4 or IPv6 addresses.
     */
    readonly recordDatas: string[];
    readonly recordType: string;
    /**
     * (Computed) (String) Specifies the sensitivity to the number of regions that need to fail for the backup record to be made active.
     */
    readonly regionFailureSensitivity: string;
    /**
     * (Computed) (String) Current status of the serving record. Valid values are:</br>
     * `OK` – Live record is being served.</br>
     * `CRITICAL` – The backup record is being served due to the monitor detecting a failure.</br>
     * `MANUAL` – The backup record is being served due to the user forcing the live record to be inactive.
     */
    readonly status: string;
    /**
     * (Computed) (Integer) The time to live (in seconds) for the record. Must be a value between 0 and 2147483647, inclusive.
     */
    readonly ttl: number;
    readonly zoneName: string;
}

export function getSfPoolOutput(args: GetSfPoolOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSfPoolResult> {
    return pulumi.output(args).apply(a => getSfPool(a, opts))
}

/**
 * A collection of arguments for invoking getSfPool.
 */
export interface GetSfPoolOutputArgs {
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    ownerName: pulumi.Input<string>;
    /**
     * (String) Must be formatted as a well-known resource record type (A or AAAA) or the corresponding number for the type (1 or 28).<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     * `AAAA (28)`
     */
    recordType: pulumi.Input<string>;
    /**
     * (String) Name of the zone.
     */
    zoneName: pulumi.Input<string>;
}
