// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this resource to manage SiteBacker (SB) pool records in UltraDNS.
 *
 * ## Example Usage
 * ### Create SB pool record of type A (1)
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ultradns from "@pulumi/ultradns";
 *
 * const sbPool = new ultradns.SbPool("a", {
 *     actOnProbes: true,
 *     backupRecords: [
 *         {
 *             failoverDelay: 1,
 *             rdata: "192.168.1.3",
 *         },
 *         {
 *             failoverDelay: 1,
 *             rdata: "192.168.1.4",
 *         },
 *     ],
 *     failureThreshold: 2,
 *     maxActive: 1,
 *     maxServed: 1,
 *     order: "ROUND_ROBIN",
 *     ownerName: "a",
 *     poolDescription: "SB Pool Resource of Type A",
 *     rdataInfos: [
 *         {
 *             failoverDelay: 2,
 *             priority: 2,
 *             rdata: "192.168.1.1",
 *             runProbes: true,
 *             state: "ACTIVE",
 *             threshold: 1,
 *         },
 *         {
 *             failoverDelay: 1,
 *             priority: 1,
 *             rdata: "192.168.1.2",
 *             runProbes: false,
 *             state: "NORMAL",
 *             threshold: 1,
 *         },
 *     ],
 *     recordType: "A",
 *     runProbes: true,
 *     ttl: 120,
 *     zoneName: "example.com.",
 * });
 * ```
 *
 * ## Import
 *
 * SiteBacker (SB) pool records can be imported by combining their `owner_name`, `zone_name`, and `record_type`, separated by a colon.<br/> Example `www.example.com.:example.com.:A (1)`. -> For import, the `owner_name` and `zone_name` must be a FQDN, and `record_type` should have the type, as well as the corresponding number, as shown in the example below. Exampleterraform
 *
 * ```sh
 *  $ pulumi import ultradns:index/sbPool:SbPool example "www.example.com.:example.com.:A (1)"
 * ```
 */
export class SbPool extends pulumi.CustomResource {
    /**
     * Get an existing SbPool resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SbPoolState, opts?: pulumi.CustomResourceOptions): SbPool {
        return new SbPool(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ultradns:index/sbPool:SbPool';

    /**
     * Returns true if the given object is an instance of SbPool.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SbPool {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SbPool.__pulumiType;
    }

    /**
     * (Boolean) Indicates whether or not pool records will be enabled (true) or disabled (false) when probes are run. Default value set to true.
     */
    public readonly actOnProbes!: pulumi.Output<boolean | undefined>;
    /**
     * (Block Set) List of nested blocks describing the information of backup records for the SiteBacker pool. Specifies the records to be served if all other records fail. There can be one or more A records used as backup records, or a single CNAME record. The structure of this block is described below.
     */
    public readonly backupRecords!: pulumi.Output<outputs.SbPoolBackupRecord[] | undefined>;
    /**
     * (Integer) The minimum number of records that must fail for a pool to be labeled 'FAILED'. If the number of failed records in the pool is greater than or equal to the 'Failure Threshold' value, the pool will be labeled FAILED.<br/>
     * For example, a pool with six priority records, one all-fail record, and the Failure Threshold value is set to four (4). If four or more priority records are not available to serve, the pool will be labeled FAILED, and the all-fail record will be served.<br/>
     * Valid value between 0 and the number of priority records in the pool.
     */
    public readonly failureThreshold!: pulumi.Output<number | undefined>;
    /**
     * (Integer) Specifies the maximum number of active servers in a pool and determines when SiteBacker takes backup servers offline.<br/>
     * For example, consider a pool with six servers. Setting Max Active to 4 means SiteBacker takes two servers offline and sends the four active records in the answer. Default value set to 1.
     */
    public readonly maxActive!: pulumi.Output<number | undefined>;
    /**
     * (Integer) Determines the number of record answers for each query. This is typically All Active records, or a subset of Max Active. Default value set to the value of `maxActive`.
     */
    public readonly maxServed!: pulumi.Output<number>;
    /**
     * (String) Indicates the order of the records returned by the resolver for the SiteBacker pool. Valid values are `FIXED`, `RANDOM`, and `ROUND_ROBIN`. Default value set to `ROUND_ROBIN`.
     */
    public readonly order!: pulumi.Output<string | undefined>;
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    public readonly ownerName!: pulumi.Output<string>;
    /**
     * (String) An optional description of the SiteBacker (SB) field.
     */
    public readonly poolDescription!: pulumi.Output<string | undefined>;
    /**
     * (Block Set) List of nested blocks describing the pool records. The structure of this block is described below.
     */
    public readonly rdataInfos!: pulumi.Output<outputs.SbPoolRdataInfo[]>;
    /**
     * (String) Must be formatted as a well-known resource record type (A), or the corresponding number for the type (1).<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     */
    public readonly recordType!: pulumi.Output<string>;
    /**
     * (Boolean) Indicates whether or not the probes are run for this pool. Default value set to true.
     */
    public readonly runProbes!: pulumi.Output<boolean | undefined>;
    /**
     * (Computed) (String)  Current status of the serving record. Valid values are:</br>
     * `OK`- If the number of records serving is equal to the Max Active value, and all the active records are top priority records.</br>
     * For example, if a pool has a Max Active of 1 and the Priority 1 record is serving.</br>
     * `WARNING` – If the number of records serving is equal to the Max Active value, and the active records are not top priority records.</br>
     * For example, if a pool has a Max Active of 1, and the Priority 1 record is not serving and the Priority 2 record is serving.</br>
     * `CRITICAL` – If the number of records serving is less than the Max Active value, or the All Fail record is being served.</br>
     * For example, if a pool has a Max Active of 2, and only one record is serving.</br>
     * `FAILED` - If the FailureThreshold value is 0 or null, and no records are serving, and there is no All Fail record configured.</br>OR</br>If the number of priority records not available to serve equals or exceeds the FailureThreshold’s value.</br>
     * For example, if the Failure Threshold value is 3, and there are 3 or more Priority Records that are not available to serve.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * (Integer) The time to live (in seconds) for the record. Must be a value between 0 and 2147483647, inclusive.
     */
    public readonly ttl!: pulumi.Output<number | undefined>;
    /**
     * (String) Name of the zone.
     */
    public readonly zoneName!: pulumi.Output<string>;

    /**
     * Create a SbPool resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SbPoolArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SbPoolArgs | SbPoolState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SbPoolState | undefined;
            resourceInputs["actOnProbes"] = state ? state.actOnProbes : undefined;
            resourceInputs["backupRecords"] = state ? state.backupRecords : undefined;
            resourceInputs["failureThreshold"] = state ? state.failureThreshold : undefined;
            resourceInputs["maxActive"] = state ? state.maxActive : undefined;
            resourceInputs["maxServed"] = state ? state.maxServed : undefined;
            resourceInputs["order"] = state ? state.order : undefined;
            resourceInputs["ownerName"] = state ? state.ownerName : undefined;
            resourceInputs["poolDescription"] = state ? state.poolDescription : undefined;
            resourceInputs["rdataInfos"] = state ? state.rdataInfos : undefined;
            resourceInputs["recordType"] = state ? state.recordType : undefined;
            resourceInputs["runProbes"] = state ? state.runProbes : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["ttl"] = state ? state.ttl : undefined;
            resourceInputs["zoneName"] = state ? state.zoneName : undefined;
        } else {
            const args = argsOrState as SbPoolArgs | undefined;
            if ((!args || args.ownerName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'ownerName'");
            }
            if ((!args || args.rdataInfos === undefined) && !opts.urn) {
                throw new Error("Missing required property 'rdataInfos'");
            }
            if ((!args || args.recordType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'recordType'");
            }
            if ((!args || args.zoneName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'zoneName'");
            }
            resourceInputs["actOnProbes"] = args ? args.actOnProbes : undefined;
            resourceInputs["backupRecords"] = args ? args.backupRecords : undefined;
            resourceInputs["failureThreshold"] = args ? args.failureThreshold : undefined;
            resourceInputs["maxActive"] = args ? args.maxActive : undefined;
            resourceInputs["maxServed"] = args ? args.maxServed : undefined;
            resourceInputs["order"] = args ? args.order : undefined;
            resourceInputs["ownerName"] = args ? args.ownerName : undefined;
            resourceInputs["poolDescription"] = args ? args.poolDescription : undefined;
            resourceInputs["rdataInfos"] = args ? args.rdataInfos : undefined;
            resourceInputs["recordType"] = args ? args.recordType : undefined;
            resourceInputs["runProbes"] = args ? args.runProbes : undefined;
            resourceInputs["ttl"] = args ? args.ttl : undefined;
            resourceInputs["zoneName"] = args ? args.zoneName : undefined;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SbPool.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SbPool resources.
 */
export interface SbPoolState {
    /**
     * (Boolean) Indicates whether or not pool records will be enabled (true) or disabled (false) when probes are run. Default value set to true.
     */
    actOnProbes?: pulumi.Input<boolean>;
    /**
     * (Block Set) List of nested blocks describing the information of backup records for the SiteBacker pool. Specifies the records to be served if all other records fail. There can be one or more A records used as backup records, or a single CNAME record. The structure of this block is described below.
     */
    backupRecords?: pulumi.Input<pulumi.Input<inputs.SbPoolBackupRecord>[]>;
    /**
     * (Integer) The minimum number of records that must fail for a pool to be labeled 'FAILED'. If the number of failed records in the pool is greater than or equal to the 'Failure Threshold' value, the pool will be labeled FAILED.<br/>
     * For example, a pool with six priority records, one all-fail record, and the Failure Threshold value is set to four (4). If four or more priority records are not available to serve, the pool will be labeled FAILED, and the all-fail record will be served.<br/>
     * Valid value between 0 and the number of priority records in the pool.
     */
    failureThreshold?: pulumi.Input<number>;
    /**
     * (Integer) Specifies the maximum number of active servers in a pool and determines when SiteBacker takes backup servers offline.<br/>
     * For example, consider a pool with six servers. Setting Max Active to 4 means SiteBacker takes two servers offline and sends the four active records in the answer. Default value set to 1.
     */
    maxActive?: pulumi.Input<number>;
    /**
     * (Integer) Determines the number of record answers for each query. This is typically All Active records, or a subset of Max Active. Default value set to the value of `maxActive`.
     */
    maxServed?: pulumi.Input<number>;
    /**
     * (String) Indicates the order of the records returned by the resolver for the SiteBacker pool. Valid values are `FIXED`, `RANDOM`, and `ROUND_ROBIN`. Default value set to `ROUND_ROBIN`.
     */
    order?: pulumi.Input<string>;
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    ownerName?: pulumi.Input<string>;
    /**
     * (String) An optional description of the SiteBacker (SB) field.
     */
    poolDescription?: pulumi.Input<string>;
    /**
     * (Block Set) List of nested blocks describing the pool records. The structure of this block is described below.
     */
    rdataInfos?: pulumi.Input<pulumi.Input<inputs.SbPoolRdataInfo>[]>;
    /**
     * (String) Must be formatted as a well-known resource record type (A), or the corresponding number for the type (1).<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     */
    recordType?: pulumi.Input<string>;
    /**
     * (Boolean) Indicates whether or not the probes are run for this pool. Default value set to true.
     */
    runProbes?: pulumi.Input<boolean>;
    /**
     * (Computed) (String)  Current status of the serving record. Valid values are:</br>
     * `OK`- If the number of records serving is equal to the Max Active value, and all the active records are top priority records.</br>
     * For example, if a pool has a Max Active of 1 and the Priority 1 record is serving.</br>
     * `WARNING` – If the number of records serving is equal to the Max Active value, and the active records are not top priority records.</br>
     * For example, if a pool has a Max Active of 1, and the Priority 1 record is not serving and the Priority 2 record is serving.</br>
     * `CRITICAL` – If the number of records serving is less than the Max Active value, or the All Fail record is being served.</br>
     * For example, if a pool has a Max Active of 2, and only one record is serving.</br>
     * `FAILED` - If the FailureThreshold value is 0 or null, and no records are serving, and there is no All Fail record configured.</br>OR</br>If the number of priority records not available to serve equals or exceeds the FailureThreshold’s value.</br>
     * For example, if the Failure Threshold value is 3, and there are 3 or more Priority Records that are not available to serve.
     */
    status?: pulumi.Input<string>;
    /**
     * (Integer) The time to live (in seconds) for the record. Must be a value between 0 and 2147483647, inclusive.
     */
    ttl?: pulumi.Input<number>;
    /**
     * (String) Name of the zone.
     */
    zoneName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SbPool resource.
 */
export interface SbPoolArgs {
    /**
     * (Boolean) Indicates whether or not pool records will be enabled (true) or disabled (false) when probes are run. Default value set to true.
     */
    actOnProbes?: pulumi.Input<boolean>;
    /**
     * (Block Set) List of nested blocks describing the information of backup records for the SiteBacker pool. Specifies the records to be served if all other records fail. There can be one or more A records used as backup records, or a single CNAME record. The structure of this block is described below.
     */
    backupRecords?: pulumi.Input<pulumi.Input<inputs.SbPoolBackupRecord>[]>;
    /**
     * (Integer) The minimum number of records that must fail for a pool to be labeled 'FAILED'. If the number of failed records in the pool is greater than or equal to the 'Failure Threshold' value, the pool will be labeled FAILED.<br/>
     * For example, a pool with six priority records, one all-fail record, and the Failure Threshold value is set to four (4). If four or more priority records are not available to serve, the pool will be labeled FAILED, and the all-fail record will be served.<br/>
     * Valid value between 0 and the number of priority records in the pool.
     */
    failureThreshold?: pulumi.Input<number>;
    /**
     * (Integer) Specifies the maximum number of active servers in a pool and determines when SiteBacker takes backup servers offline.<br/>
     * For example, consider a pool with six servers. Setting Max Active to 4 means SiteBacker takes two servers offline and sends the four active records in the answer. Default value set to 1.
     */
    maxActive?: pulumi.Input<number>;
    /**
     * (Integer) Determines the number of record answers for each query. This is typically All Active records, or a subset of Max Active. Default value set to the value of `maxActive`.
     */
    maxServed?: pulumi.Input<number>;
    /**
     * (String) Indicates the order of the records returned by the resolver for the SiteBacker pool. Valid values are `FIXED`, `RANDOM`, and `ROUND_ROBIN`. Default value set to `ROUND_ROBIN`.
     */
    order?: pulumi.Input<string>;
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    ownerName: pulumi.Input<string>;
    /**
     * (String) An optional description of the SiteBacker (SB) field.
     */
    poolDescription?: pulumi.Input<string>;
    /**
     * (Block Set) List of nested blocks describing the pool records. The structure of this block is described below.
     */
    rdataInfos: pulumi.Input<pulumi.Input<inputs.SbPoolRdataInfo>[]>;
    /**
     * (String) Must be formatted as a well-known resource record type (A), or the corresponding number for the type (1).<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     */
    recordType: pulumi.Input<string>;
    /**
     * (Boolean) Indicates whether or not the probes are run for this pool. Default value set to true.
     */
    runProbes?: pulumi.Input<boolean>;
    /**
     * (Integer) The time to live (in seconds) for the record. Must be a value between 0 and 2147483647, inclusive.
     */
    ttl?: pulumi.Input<number>;
    /**
     * (String) Name of the zone.
     */
    zoneName: pulumi.Input<string>;
}
