// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this resource to manage Simple Load Balancing (SLB) pool records in UltraDNS.
 *
 * ## Example Usage
 * ### Create SLB pool record of type A (1)
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ultradns from "@pulumi/ultradns";
 *
 * const slbPool = new ultradns.SlbPool("a", {
 *     allFailRecord: {
 *         rdata: "192.127.127.33",
 *     },
 *     monitor: {
 *         method: "POST",
 *         url: "https://example.com",
 *     },
 *     ownerName: "a",
 *     rdataInfos: [
 *         {
 *             description: "first",
 *             probingEnabled: false,
 *             rdata: "192.201.127.33",
 *         },
 *         {
 *             description: "second",
 *             probingEnabled: true,
 *             rdata: "192.168.1.2",
 *         },
 *     ],
 *     recordType: "A",
 *     regionFailureSensitivity: "HIGH",
 *     responseMethod: "ROUND_ROBIN",
 *     servingPreference: "AUTO_SELECT",
 *     ttl: 120,
 *     zoneName: "example.com.",
 * });
 * ```
 * ### Create SLB pool record of type AAAA (28)
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ultradns from "@pulumi/ultradns";
 *
 * const aaaa = new ultradns.SlbPool("aaaa", {
 *     allFailRecord: {
 *         rdata: "2001:db8:85a3:0:0:8a2e:370:7324",
 *     },
 *     monitor: {
 *         method: "GET",
 *         url: "https://example.com",
 *     },
 *     ownerName: "aaaa",
 *     rdataInfos: [{
 *         description: "first",
 *         probingEnabled: false,
 *         rdata: "2001:db8:85a3:0:0:8a2e:370:7334",
 *     }],
 *     recordType: "28",
 *     regionFailureSensitivity: "LOW",
 *     responseMethod: "ROUND_ROBIN",
 *     servingPreference: "AUTO_SELECT",
 *     ttl: 120,
 *     zoneName: "example.com.",
 * });
 * ```
 *
 * ## Import
 *
 * Simple Load Balancing (SLB) pool records can be imported by combining their `owner_name`, `zone_name`, and `record_type`, separated by a colon.<br/> Example `www.example.com.:example.com.:A (1)`. -> For import, the `owner_name` and `zone_name` must be a FQDN, and `record_type` should have the type, as well as the corresponding number, as shown in the example below. Exampleterraform
 *
 * ```sh
 *  $ pulumi import ultradns:index/slbPool:SlbPool example "www.example.com.:example.com.:A (1)"
 * ```
 */
export class SlbPool extends pulumi.CustomResource {
    /**
     * Get an existing SlbPool resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SlbPoolState, opts?: pulumi.CustomResourceOptions): SlbPool {
        return new SlbPool(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ultradns:index/slbPool:SlbPool';

    /**
     * Returns true if the given object is an instance of SlbPool.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SlbPool {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SlbPool.__pulumiType;
    }

    /**
     * (Block Set) Nested block describing the information for the backup record. The structure of this block is described below.
     */
    public readonly allFailRecord!: pulumi.Output<outputs.SlbPoolAllFailRecord>;
    /**
     * (Block Set) Nested block describing the information for the monitor. The structure of this block is described below.
     */
    public readonly monitor!: pulumi.Output<outputs.SlbPoolMonitor>;
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    public readonly ownerName!: pulumi.Output<string>;
    /**
     * (String) An optional description of the Simple Load Balancing (SLB) field.
     */
    public readonly poolDescription!: pulumi.Output<string | undefined>;
    /**
     * (Block Set, Max: 5) Nested block describing the pool records. The structure of this block is described below.
     */
    public readonly rdataInfos!: pulumi.Output<outputs.SlbPoolRdataInfo[]>;
    /**
     * (String) Must be formatted as a well-known resource record type (A or AAAA), or the corresponding number for the type (1 or 28).<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     * `AAAA (28)`
     */
    public readonly recordType!: pulumi.Output<string>;
    /**
     * (String) Specifies the sensitivity to the number of regions that need to fail for the backup record to be made active. Valid values are `LOW`, and `HIGH`.
     */
    public readonly regionFailureSensitivity!: pulumi.Output<string>;
    /**
     * (String) The method used to select which record is returned from the primary record pool. Valid values are:</br>
     * `PRIORITY_HUNT` – The sequence of the records listed in the primary record pool determines the priority. The first record listed is the highest priority record. Once a record starts being served, it will always be served until the probe detects a failure on this record, or, the record is set to FORCED_INACTIVE.</br>
     * `RANDOM` – A random record is returned from the following set of primary records.</br>
     * `ROUND_ROBIN` -A record is returned in (a round robin fashion) rotation, based upon the priority of the following active set of records.
     */
    public readonly responseMethod!: pulumi.Output<string>;
    /**
     * (String) It determines if records will be selected from the Primary Records pool or from the All Fail Record. Valid values are:</br>
     * `AUTO_SELECT`: Serving method switches from serving Primary Records, to All Fail Record based upon probe results, and the Forced State of the Primary Records.</br>
     * `SERVE_PRIMARY`: Only the Primary Records are served based upon the probe results and the Forced State of the Primary Records.</br>
     * `SERVE_ALL_FAIL`: Only the All Fail Record will be served, ignoring the probe results and the Forced State of the Primary Records.
     */
    public readonly servingPreference!: pulumi.Output<string>;
    /**
     * (Computed) (String)  Current status of the serving record. Valid values are:</br>
     * `OK`- Priority record(s) are being served.</br>
     * `WARNING` – One of the priority records is not being served due to the monitor detecting a failure, but there is still a priority record to be served.</br>
     * `CRITICAL` – The backup All Fail record is being served due to the monitor detecting a failure.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * (Integer) The time to live (in seconds) for the record. Must be a value between 0 and 2147483647, inclusive.
     */
    public readonly ttl!: pulumi.Output<number | undefined>;
    /**
     * (String) Name of the zone.
     */
    public readonly zoneName!: pulumi.Output<string>;

    /**
     * Create a SlbPool resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SlbPoolArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SlbPoolArgs | SlbPoolState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SlbPoolState | undefined;
            resourceInputs["allFailRecord"] = state ? state.allFailRecord : undefined;
            resourceInputs["monitor"] = state ? state.monitor : undefined;
            resourceInputs["ownerName"] = state ? state.ownerName : undefined;
            resourceInputs["poolDescription"] = state ? state.poolDescription : undefined;
            resourceInputs["rdataInfos"] = state ? state.rdataInfos : undefined;
            resourceInputs["recordType"] = state ? state.recordType : undefined;
            resourceInputs["regionFailureSensitivity"] = state ? state.regionFailureSensitivity : undefined;
            resourceInputs["responseMethod"] = state ? state.responseMethod : undefined;
            resourceInputs["servingPreference"] = state ? state.servingPreference : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["ttl"] = state ? state.ttl : undefined;
            resourceInputs["zoneName"] = state ? state.zoneName : undefined;
        } else {
            const args = argsOrState as SlbPoolArgs | undefined;
            if ((!args || args.allFailRecord === undefined) && !opts.urn) {
                throw new Error("Missing required property 'allFailRecord'");
            }
            if ((!args || args.monitor === undefined) && !opts.urn) {
                throw new Error("Missing required property 'monitor'");
            }
            if ((!args || args.ownerName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'ownerName'");
            }
            if ((!args || args.rdataInfos === undefined) && !opts.urn) {
                throw new Error("Missing required property 'rdataInfos'");
            }
            if ((!args || args.recordType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'recordType'");
            }
            if ((!args || args.regionFailureSensitivity === undefined) && !opts.urn) {
                throw new Error("Missing required property 'regionFailureSensitivity'");
            }
            if ((!args || args.responseMethod === undefined) && !opts.urn) {
                throw new Error("Missing required property 'responseMethod'");
            }
            if ((!args || args.servingPreference === undefined) && !opts.urn) {
                throw new Error("Missing required property 'servingPreference'");
            }
            if ((!args || args.zoneName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'zoneName'");
            }
            resourceInputs["allFailRecord"] = args ? args.allFailRecord : undefined;
            resourceInputs["monitor"] = args ? args.monitor : undefined;
            resourceInputs["ownerName"] = args ? args.ownerName : undefined;
            resourceInputs["poolDescription"] = args ? args.poolDescription : undefined;
            resourceInputs["rdataInfos"] = args ? args.rdataInfos : undefined;
            resourceInputs["recordType"] = args ? args.recordType : undefined;
            resourceInputs["regionFailureSensitivity"] = args ? args.regionFailureSensitivity : undefined;
            resourceInputs["responseMethod"] = args ? args.responseMethod : undefined;
            resourceInputs["servingPreference"] = args ? args.servingPreference : undefined;
            resourceInputs["ttl"] = args ? args.ttl : undefined;
            resourceInputs["zoneName"] = args ? args.zoneName : undefined;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SlbPool.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SlbPool resources.
 */
export interface SlbPoolState {
    /**
     * (Block Set) Nested block describing the information for the backup record. The structure of this block is described below.
     */
    allFailRecord?: pulumi.Input<inputs.SlbPoolAllFailRecord>;
    /**
     * (Block Set) Nested block describing the information for the monitor. The structure of this block is described below.
     */
    monitor?: pulumi.Input<inputs.SlbPoolMonitor>;
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    ownerName?: pulumi.Input<string>;
    /**
     * (String) An optional description of the Simple Load Balancing (SLB) field.
     */
    poolDescription?: pulumi.Input<string>;
    /**
     * (Block Set, Max: 5) Nested block describing the pool records. The structure of this block is described below.
     */
    rdataInfos?: pulumi.Input<pulumi.Input<inputs.SlbPoolRdataInfo>[]>;
    /**
     * (String) Must be formatted as a well-known resource record type (A or AAAA), or the corresponding number for the type (1 or 28).<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     * `AAAA (28)`
     */
    recordType?: pulumi.Input<string>;
    /**
     * (String) Specifies the sensitivity to the number of regions that need to fail for the backup record to be made active. Valid values are `LOW`, and `HIGH`.
     */
    regionFailureSensitivity?: pulumi.Input<string>;
    /**
     * (String) The method used to select which record is returned from the primary record pool. Valid values are:</br>
     * `PRIORITY_HUNT` – The sequence of the records listed in the primary record pool determines the priority. The first record listed is the highest priority record. Once a record starts being served, it will always be served until the probe detects a failure on this record, or, the record is set to FORCED_INACTIVE.</br>
     * `RANDOM` – A random record is returned from the following set of primary records.</br>
     * `ROUND_ROBIN` -A record is returned in (a round robin fashion) rotation, based upon the priority of the following active set of records.
     */
    responseMethod?: pulumi.Input<string>;
    /**
     * (String) It determines if records will be selected from the Primary Records pool or from the All Fail Record. Valid values are:</br>
     * `AUTO_SELECT`: Serving method switches from serving Primary Records, to All Fail Record based upon probe results, and the Forced State of the Primary Records.</br>
     * `SERVE_PRIMARY`: Only the Primary Records are served based upon the probe results and the Forced State of the Primary Records.</br>
     * `SERVE_ALL_FAIL`: Only the All Fail Record will be served, ignoring the probe results and the Forced State of the Primary Records.
     */
    servingPreference?: pulumi.Input<string>;
    /**
     * (Computed) (String)  Current status of the serving record. Valid values are:</br>
     * `OK`- Priority record(s) are being served.</br>
     * `WARNING` – One of the priority records is not being served due to the monitor detecting a failure, but there is still a priority record to be served.</br>
     * `CRITICAL` – The backup All Fail record is being served due to the monitor detecting a failure.
     */
    status?: pulumi.Input<string>;
    /**
     * (Integer) The time to live (in seconds) for the record. Must be a value between 0 and 2147483647, inclusive.
     */
    ttl?: pulumi.Input<number>;
    /**
     * (String) Name of the zone.
     */
    zoneName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SlbPool resource.
 */
export interface SlbPoolArgs {
    /**
     * (Block Set) Nested block describing the information for the backup record. The structure of this block is described below.
     */
    allFailRecord: pulumi.Input<inputs.SlbPoolAllFailRecord>;
    /**
     * (Block Set) Nested block describing the information for the monitor. The structure of this block is described below.
     */
    monitor: pulumi.Input<inputs.SlbPoolMonitor>;
    /**
     * (String) The domain name of the owner of the RRSet. Can be either a fully qualified domain name (FQDN) or a relative domain name. If provided as a FQDN, it must be contained within the zone name's FQDN.
     */
    ownerName: pulumi.Input<string>;
    /**
     * (String) An optional description of the Simple Load Balancing (SLB) field.
     */
    poolDescription?: pulumi.Input<string>;
    /**
     * (Block Set, Max: 5) Nested block describing the pool records. The structure of this block is described below.
     */
    rdataInfos: pulumi.Input<pulumi.Input<inputs.SlbPoolRdataInfo>[]>;
    /**
     * (String) Must be formatted as a well-known resource record type (A or AAAA), or the corresponding number for the type (1 or 28).<br/>
     * Below are the supported resource record types with the corresponding number:<br/>
     * `A (1)`
     * `AAAA (28)`
     */
    recordType: pulumi.Input<string>;
    /**
     * (String) Specifies the sensitivity to the number of regions that need to fail for the backup record to be made active. Valid values are `LOW`, and `HIGH`.
     */
    regionFailureSensitivity: pulumi.Input<string>;
    /**
     * (String) The method used to select which record is returned from the primary record pool. Valid values are:</br>
     * `PRIORITY_HUNT` – The sequence of the records listed in the primary record pool determines the priority. The first record listed is the highest priority record. Once a record starts being served, it will always be served until the probe detects a failure on this record, or, the record is set to FORCED_INACTIVE.</br>
     * `RANDOM` – A random record is returned from the following set of primary records.</br>
     * `ROUND_ROBIN` -A record is returned in (a round robin fashion) rotation, based upon the priority of the following active set of records.
     */
    responseMethod: pulumi.Input<string>;
    /**
     * (String) It determines if records will be selected from the Primary Records pool or from the All Fail Record. Valid values are:</br>
     * `AUTO_SELECT`: Serving method switches from serving Primary Records, to All Fail Record based upon probe results, and the Forced State of the Primary Records.</br>
     * `SERVE_PRIMARY`: Only the Primary Records are served based upon the probe results and the Forced State of the Primary Records.</br>
     * `SERVE_ALL_FAIL`: Only the All Fail Record will be served, ignoring the probe results and the Forced State of the Primary Records.
     */
    servingPreference: pulumi.Input<string>;
    /**
     * (Integer) The time to live (in seconds) for the record. Must be a value between 0 and 2147483647, inclusive.
     */
    ttl?: pulumi.Input<number>;
    /**
     * (String) Name of the zone.
     */
    zoneName: pulumi.Input<string>;
}
